### ISSUE TITLE
Run in GUI-less mode

### ISSUE THREAD

**Issue by femangl** [huxi/lilith#18]
Hi,

First of all: great piece of software here :) I have the following use-case for Lilith and wanted to ask if this is possible:

I have an application which is running on multiple hosts in my network environment. I want to collect all log messages of these application instances on a single machine. This works great with Lilith as it is and I collected experience with it.

Now is my question: is it possible to run Lilith with no GUI? I want to start Lilith as Log-Server on a pure command line based server and download in regular time periods the log files and check the downloaded logs with a different lilith instance.

Kind regards,
Felix

**Comment by aadrian** [comment]
@huxi any news on this feature?

A headless Server/Collector/proxy mode would be very helpful now that with the "cloud" there are many more virtual hosts in use.

> you can instruct Logback to write Lilith files

This is unfortunately not an option in many environments. 

Thank you.

**Comment by huxi** [comment]
You should consider using something like [Logstash](https://www.elastic.co/logstash) for the cloud instead.

Chances are bad that I'll implement this because it would boil down to rewriting a 10y old code-base. If I'd actually do something like that, I'd probably rather implement it in Rust instead Java.

I'll close this issue now because I won't find the time and motivation to implement this.
