### ISSUE TITLE
Is it possible to connect lilith to external server?

### ISSUE THREAD

**Issue by Silnar** [huxi/lilith#20]
Hi,

Lilith works great on a local machine, but is it possible to receive logs from external server ?

Cheers.

**Comment by huxi** [comment]
If the external server can connect to the relevant open Lilith port then yes.

You are probably behind a firewall/NAT and would need to configure port forwarding. If you have a dynamic IP address you'd also need to change it in the logback config accordingly.

Anyway: that's not a Lilith issue so I'll close it.

Hope that helps.

Cheers,
Jörn.

**Comment by Silnar** [comment]
Hmm, what with doing it other way round...
To setup a 'log server' that lilith could connect to?
Is it possible ?

Cheers.

**Comment by huxi** [comment]
This is supported by log4j and Logback (recently) but is unsupported by Lilith.

The thing is that doing so is basically a security nightmare. Anybody could connect to that port and just linger, causing the application to grind to a halt if the event buffer fills up to the brim, making it perfect for a DoS attack.

It wouldn't be too hard to support this in Lilith (I guess) but I don't want to encourage people to use a potentially dangerous feature...

**Comment by Silnar** [comment]
> This is supported by log4j and Logback (recently) but is unsupported by Lilith.

I'm using logback. Do you mean [ServerSocketAppender](http://logback.qos.ch/manual/receivers.html#receiverClientComponents) ?

> The thing is that doing so is basically a security nightmare. Anybody could connect to that port and just linger, causing the application to grind to a halt if the event buffer fills up to the brim, making it perfect for a DoS attack.

Wouldn't it be a matter of securing it somehow?
Allowing access from selected IPs only or maybe setting up a dedicated VPN?

**Comment by huxi** [comment]
Yes, `ServerSocketAppender`.

The thing is:
if you are using a VPN you could simply use `SocketAppender` instead since you'd then have a dedicated non-dynamic IP address in the VPN. That's how we use Logback+Lilith in the production environment of the company I work at and that's the "proper" way regarding security.

If I'd support `ServerSocketAppender` then I suspect people wouldn't even think twice about issues like that because "it works" - until something bad happens.
